# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0001_initial"),
        ("contacts", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this carrier belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carriers",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="carrier",
            index=models.Index(
                fields=["tenant", "name"], name="carriers_ca_tenant__8e23de_idx"
            ),
        ),
    ]
