# Optional Pre-commit Hooks for Frontend

# These hooks can be added to .pre-commit-config.yaml for frontend code quality.
# They are separated here because they require Node.js dependencies and network access
# to install, which may not be available in all environments.

# To enable these hooks, add them to the main .pre-commit-config.yaml file.

# TypeScript/JavaScript formatting with Prettier
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
    - id: prettier
      files: \.(ts|tsx|js|jsx|json|css|md)$
      exclude: ^(backend/|\.venv/|venv/|node_modules/)
      additional_dependencies:
        - prettier@3.1.0
        - '@typescript-eslint/parser@6.13.0'

# Markdown linting
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.37.0
  hooks:
    - id: markdownlint
      args: ['--fix']
      files: \.md$
      exclude: ^(node_modules/|\.venv/)
