version: "3.8"

networks:
  edge:        # public edge (Traefik + app services that must be reachable)
  app:         # private app network (DB/cache/backend)

volumes:
  letsencrypt:   # Traefik ACME store
  pg_data:
  valkey_data:

services:
  traefik:
    image: traefik:v3.5.2
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Redirect all HTTP to HTTPS
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - edge

  api:
    image: ${IMAGE_TAG_BACKEND}
    restart: unless-stopped
    env_file:
      - env/dev.env
      - env/image.env
    # depends_on:
    #   - postgres
    #   - valkey
    labels:
      - "traefik.enable=true"
      # Catch everything on the host (except api which has higher priority)
      - "traefik.http.routers.api-dev.rule=Host(`${API_DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.api-dev.priority=10"         # lower than API
      - "traefik.http.routers.api-dev.entrypoints=websecure"
      - "traefik.http.routers.api-dev.tls=true"
      - "traefik.http.routers.api-dev.tls.certresolver=le"
      - "traefik.http.services.api-dev.loadbalancer.server.port=8000"


    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - edge
      - app

  web:
    image: ${IMAGE_TAG_FRONTEND}
    restart: unless-stopped
    env_file:
      - env/dev.env
      - env/image.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-dev.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.web-dev.entrypoints=websecure"
      - "traefik.http.routers.web-dev.tls=true"
      - "traefik.http.routers.web-dev.tls.certresolver=le"
      - "traefik.http.services.web-dev.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/healthz"]
    networks:
      - edge

  # postgres:
  #   image: postgres:16
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-meats}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-meats}
  #     POSTGRES_DB: ${POSTGRES_DB:-meats}
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   networks:
  #     - app

  # valkey:
  #   image: valkey/valkey:7
  #   restart: unless-stopped
  #   command: ["valkey-server", "--requirepass", "${VALKEY_PASSWORD:-meats}"]
  #   volumes:
  #     - valkey_data:/data
  #   networks:
  #     - app
