# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_tenant_and_more"),
        ("core", "0001_initial"),
        ("customers", "0001_initial"),
        ("plants", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this customer belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "name"], name="customers_c_tenant__5b0286_idx"
            ),
        ),
    ]
