# Generated by Django 4.2.7 on 2025-09-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Protein type (e.g., Beef, Pork, Chicken, Lamb)",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Protein",
                "verbose_name_plural": "Proteins",
                "ordering": ["name"],
            },
        ),
    ]
