# Generated by Django 4.2.7 on 2025-11-03 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        help_text="UI theme preference",
                        max_length=20,
                    ),
                ),
                (
                    "dashboard_layout",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dashboard widget layout configuration",
                    ),
                ),
                (
                    "sidebar_collapsed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether sidebar is collapsed by default",
                    ),
                ),
                (
                    "quick_menu_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User's favorite quick menu items",
                    ),
                ),
                (
                    "widget_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Widget-specific preferences and configurations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User for these preferences",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "ordering": ["-updated_at"],
            },
        ),
    ]
