# Generated by Django 4.2.7 on 2025-11-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_userpreferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or description of the quota", max_length=100
                    ),
                ),
                (
                    "quota_amount",
                    models.IntegerField(
                        default=0, help_text="Quota amount (e.g., sales target)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quota",
                "verbose_name_plural": "Quotas",
                "ordering": ["name"],
            },
        ),
    ]
