# Generated by Django 4.2.7 on 2025-12-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0002_initial"),
        ("sales_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Related sales order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales_orders.salesorder",
            ),
        ),
    ]
