# Generated by Django 4.2.7 on 2025-12-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carriers", "0001_initial"),
        ("plants", "0001_initial"),
        ("products", "0002_initial"),
        ("sales_orders", "0001_initial"),
        ("purchase_orders", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Supplier for this purchase order",
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="coldstorageentry",
            name="customer_sales_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Related customer sales order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cold_storage_entries",
                to="sales_orders.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="coldstorageentry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product being stored",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="coldstorageentry",
            name="supplier_po",
            field=models.ForeignKey(
                blank=True,
                help_text="Related supplier purchase order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cold_storage_entries",
                to="purchase_orders.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="carrier",
            field=models.ForeignKey(
                help_text="Carrier for this purchase order",
                on_delete=django.db.models.deletion.CASCADE,
                to="carriers.carrier",
            ),
        ),
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Plant/facility for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product being ordered",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Supplier for this carrier purchase order",
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderhistory",
            index=models.Index(
                fields=["purchase_order", "-created_on"],
                name="purchase_or_purchas_dafcda_idx",
            ),
        ),
    ]
