# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0002_carrier_tenant_and_more"),
        ("contacts", "0002_contact_tenant_and_more"),
        ("plants", "0002_plant_tenant_plant_plants_plan_tenant__9efb37_idx_and_more"),
        ("products", "0002_product_tenant"),
        ("purchase_orders", "0001_initial"),
        ("sales_orders", "0001_initial"),
        (
            "suppliers",
            "0003_rename_suppliers_s_tenant__idx_suppliers_s_tenant__566edc_idx",
        ),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this carrier purchase order belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrier_purchase_orders",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coldstorageentry",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this cold storage entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cold_storage_entries",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this purchase order belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorderhistory",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this history entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_histories",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="carrierpurchaseorder",
            index=models.Index(
                fields=["tenant", "our_carrier_po_num"],
                name="purchase_or_tenant__6ab6fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coldstorageentry",
            index=models.Index(
                fields=["tenant", "date_time_stamp_created"],
                name="purchase_or_tenant__d5379c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["tenant", "order_number"], name="purchase_or_tenant__e12583_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["tenant", "order_date"], name="purchase_or_tenant__e60062_idx"
            ),
        ),
    ]
