# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.db import migrations, models




def add_tenant_field_if_not_exists(apps, schema_editor):
    """Add tenant field only if it doesn't exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if tenant_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name=%s 
            AND column_name='tenant_id';
        """, ['purchase_orders_carrierpurchaseorder'])
        
        if not cursor.fetchone():
            # Check if any tenants exist
            cursor.execute("SELECT id FROM tenants_tenant LIMIT 1;")
            result = cursor.fetchone()
            
            if result:
                # Production path: Tenant exists, use it as default
                default_tenant_id = result[0]
                cursor.execute("""
                    ALTER TABLE purchase_orders_carrierpurchaseorder 
                    ADD COLUMN tenant_id UUID NOT NULL DEFAULT %s 
                    REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;
                """, [default_tenant_id])
                
                # Remove the default after adding the column
                cursor.execute("""
                    ALTER TABLE purchase_orders_carrierpurchaseorder 
                    ALTER COLUMN tenant_id DROP DEFAULT;
                """)
            else:
                # Test/Fresh DB path: No tenants exist yet, add as nullable
                cursor.execute("""
                    ALTER TABLE purchase_orders_carrierpurchaseorder 
                    ADD COLUMN tenant_id UUID NULL 
                    REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;
                """)


def add_indexes_if_not_exist(apps, schema_editor):
    """Add indexes only if they don't exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Get all indexes that should exist
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename=%s AND indexname LIKE %s;
        """, ['purchase_orders_carrierpurchaseorder', f'purchase_orders_%'])
        
        existing_indexes = {row[0] for row in cursor.fetchall()}
        
        # This will be filled with actual index creation SQL if we find any
        # For now, we'll let Django's index management handle it
        pass

class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0002_carrier_tenant_and_more"),
        ("contacts", "0002_contact_tenant_and_more"),
        ("plants", "0002_plant_tenant_plant_plants_plan_tenant__9efb37_idx_and_more"),
        ("products", "0002_product_tenant"),
        ("purchase_orders", "0001_initial"),
        ("sales_orders", "0001_initial"),
        (
            "suppliers",
            "0003_rename_suppliers_s_tenant__idx_suppliers_s_tenant__566edc_idx",
        ),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_tenant_field_if_not_exists, migrations.RunPython.noop),
        preserve_default=False,
        ),
        migrations.AddField(
            model_name="coldstorageentry",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this cold storage entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cold_storage_entries",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this purchase order belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorderhistory",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this history entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_order_histories",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="carrierpurchaseorder",
            index=models.Index(
                fields=["tenant", "our_carrier_po_num"],
                name="purchase_or_tenant__6ab6fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coldstorageentry",
            index=models.Index(
                fields=["tenant", "date_time_stamp_created"],
                name="purchase_or_tenant__d5379c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["tenant", "order_number"], name="purchase_or_tenant__e12583_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["tenant", "order_date"], name="purchase_or_tenant__e60062_idx"
            ),
        ),
    ]
