# Generated by Django 4.2.7 on 2025-12-04 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrierpurchaseorder",
            name="linked_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the associated Supplier Purchase Order (SupplierPO). This creates the logistics bridge to track which carrier is hauling which supplier order.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carrier_logistics",
                to="purchase_orders.purchaseorder",
            ),
        ),
    ]
