# Generated by Django 6.0 on 2026-01-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Golden State Synchronization: Inform Django that tenant fields exist."""

    dependencies = [
        ("purchase_orders", "0003_add_logistics_bridges_and_verbose_names"),
        ("tenants", "0004_add_golden_ticket_features"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="purchaseorder",
                    name="tenant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="tenants.tenant",
                        help_text="Tenant this purchase order belongs to",
                    ),
                ),
                migrations.AddField(
                    model_name="carrierpurchaseorder",
                    name="tenant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrier_purchase_orders",
                        to="tenants.tenant",
                        help_text="Tenant this carrier purchase order belongs to",
                    ),
                ),
                migrations.AddField(
                    model_name="coldstorageentry",
                    name="tenant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cold_storage_entries",
                        to="tenants.tenant",
                        help_text="Tenant this cold storage entry belongs to",
                    ),
                ),
                migrations.AddField(
                    model_name="purchaseorderhistory",
                    name="tenant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_order_histories",
                        to="tenants.tenant",
                        help_text="Tenant this history entry belongs to",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
