# Generated by Django 4.2.7 on 2025-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="cell_phone",
            field=models.CharField(
                blank=True, help_text="Cell phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_title",
            field=models.CharField(
                blank=True, help_text="Contact title/designation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sales", "Sales"),
                    ("Accounting", "Accounting"),
                    ("Shipping", "Shipping"),
                    ("Receiving", "Receiving"),
                    ("Operations", "Operations"),
                    ("Quality", "Quality"),
                    ("Executive", "Executive"),
                ],
                help_text="Type of contact (e.g., Sales, Accounting, Shipping)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="direct_phone",
            field=models.CharField(
                blank=True, help_text="Direct phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="main_phone",
            field=models.CharField(
                blank=True, help_text="Main phone number", max_length=20
            ),
        ),
    ]
