# Generated by Django 6.0 on 2026-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0003_add_logistics_indexes"),
        ("contacts", "0002_contact_tenant_and_more"),
        ("customers", "0003_customer_contact_title_alter_customer_industry"),
        ("plants", "0004_metadata_lockdown"),
        ("products", "0004_state_sync_tenant"),
        ("sales_orders", "0004_state_sync_tenant"),
        (
            "suppliers",
            "0003_rename_suppliers_s_tenant__idx_suppliers_s_tenant__566edc_idx",
        ),
        ("tenants", "0005_metadata_lockdown"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["tenant", "our_sales_order_num"],
                name="sales_order_tenant__027d51_idx",
            ),
        ),
    ]
