# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this plant belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plants",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(
                fields=["tenant", "code"], name="plants_plan_tenant__9efb37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(
                fields=["tenant", "name"], name="plants_plan_tenant__00c5a7_idx"
            ),
        ),
    ]
