# Generated by Django 6.0 on 2026-01-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Golden State Synchronization: Inform Django that tenant field exists."""

    dependencies = [
        ("plants", "0002_plant_tenant_plant_plants_plan_tenant__9efb37_idx_and_more"),
        ("tenants", "0004_add_golden_ticket_features"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="plant",
                    name="tenant",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plants",
                        to="tenants.tenant",
                        help_text="Tenant this plant belongs to",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
