# Generated by Django 6.0 on 2026-01-10 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0004_metadata_lockdown"),
        ("suppliers", "0005_supplier_departments_array"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier that owns/operates this plant",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_plants",
                to="suppliers.supplier",
            ),
        ),
    ]
