# Generated by Django 6.0 on 2026-01-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0005_plant_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="plant",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="plant",
            name="zip_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
