# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this product belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
    ]
