# Generated by Django 4.2.7 on 2025-12-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier for this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="suppliers.supplier",
            ),
        ),
    ]
