# AI Agent Instructions for ProjectMeats
# Applies to GitHub Copilot, Cursor, and other coding assistants

project:
  name: "ProjectMeats"
  description: "Multi-tenant PowerApps migration to Django + React"
  
architecture:
  multi_tenancy:
    type: "shared-schema"
    rules:
      - "NEVER use django-tenants mixins or schema_context()"
      - "ALWAYS filter by tenant=request.tenant in ViewSets"
      - "Use standard Django migrate command only"
  
  tech_stack:
    backend: "Django 5.x + DRF + PostgreSQL"
    frontend: "React 19.2.1 + TypeScript 5.9"
    mobile: "React Native"
  
standards:
  code_quality:
    python:
      - "PEP 8 compliance"
      - "Type hints for public functions"
      - "Black formatter"
      - "Max line length: 120"
    
    typescript:
      - "Airbnb ESLint config"
      - "Strict mode enabled"
      - "Functional components preferred"
      - "No any types"
  
  ethics:
    - "Bias mitigation in AI features"
    - "Transparency in AI-driven decisions"
    - "Privacy-first: no training on customer data without consent"
    - "Human oversight for critical operations"
    - "Sustainability: optimize compute resources"
  
  security:
    - "OWASP Top 10 awareness"
    - "Dependency scanning via Dependabot"
    - "No secrets in code"
    - "Tenant isolation testing mandatory"

workflows:
  branching:
    - "Create feature branches from development"
    - "PR to development → automated PR to UAT → automated PR to main"
    - "NEVER push directly to uat or main"
  
  testing:
    - "Backend: python manage.py test apps/ --verbosity=2"
    - "Frontend: npm run test"
    - "80%+ coverage goal"
  
  deployment:
    - "Migrations: python manage.py migrate --fake-initial --noinput"
    - "No migrate_schemas commands"
    - "Health checks: /api/v1/health/"

copilot_limits:
  - "Keep suggestions concise (avoid verbose explanations)"
  - "Use existing project structures (avoid new external installs)"
  - "Reference docs/ for architectural decisions"
  - "Limit generated code to ~200 lines per suggestion"
  - "Atomic commits with semantic messages"
