# ProjectMeats AI Agent Configuration
# Version: 1.0.0 | December 2025

# =============================================================================
# CRITICAL RULES FOR ALL AI AGENTS
# =============================================================================

rules:
  # Multi-Tenancy Architecture
  multi_tenancy:
    architecture: "shared-schema"
    never_use:
      - "django-tenants"
      - "TenantMixin"
      - "DomainMixin"
      - "schema_context()"
      - "connection.schema_name"
      - "migrate_schemas"
    always_use:
      - "tenant ForeignKey on business models"
      - "filter(tenant=request.tenant)"
      - "python manage.py migrate"
    description: >
      ProjectMeats uses SHARED SCHEMA multi-tenancy. All tenants share one
      PostgreSQL schema. Tenant isolation is via tenant_id foreign keys.

  # Code Standards
  code_standards:
    backend:
      framework: "Django 5.x + DRF"
      linting: "black, isort, flake8"
      max_line_length: 100
    frontend:
      framework: "React 19 + TypeScript 5.9"
      linting: "ESLint (Airbnb config) + Prettier"
      max_line_length: 120

  # Ethical AI Guidelines
  ethical_ai:
    - "Never generate content that could be harmful"
    - "Respect copyright and intellectual property"
    - "Do not generate sensitive data (PII, credentials)"
    - "Maintain security best practices"
    - "Follow OWASP guidelines for security"

  # Prompt Limits
  prompt_limits:
    max_file_changes: 10
    max_lines_per_change: 200
    require_tests: true
    require_documentation_update: true

# =============================================================================
# PROJECT OVERVIEW
# =============================================================================

project:
  name: "ProjectMeats"
  description: "Meat sales broker management system"
  tech_stack:
    backend: "Django 5.x + DRF + PostgreSQL"
    frontend: "React 19 + TypeScript 5.9 + Vite"
    mobile: "React Native"
  architecture:
    multi_tenancy: "Shared schema with tenant_id ForeignKeys"
    api: "REST via /api/v1/"
    auth: "Token + Session authentication"

# =============================================================================
# WORKFLOW PATTERNS
# =============================================================================

patterns:
  viewset_tenant_isolation: |
    class MyViewSet(viewsets.ModelViewSet):
        def get_queryset(self):
            return super().get_queryset().filter(tenant=self.request.tenant)
        
        def perform_create(self, serializer):
            serializer.save(tenant=self.request.tenant)

  model_with_tenant: |
    class MyModel(models.Model):
        tenant = models.ForeignKey(
            'tenants.Tenant',
            on_delete=models.CASCADE,
            related_name='my_models'
        )
        # ... other fields

  migration_commands: |
    # Standard Django migrations (NO migrate_schemas)
    python manage.py makemigrations
    python manage.py migrate
    python manage.py makemigrations --check

# =============================================================================
# DEPLOYMENT RULES
# =============================================================================

deployment:
  branch_workflow:
    - "feature/* → development (via PR)"
    - "development → UAT (automated PR)"
    - "UAT → main (automated PR)"
  never:
    - "Push directly to UAT"
    - "Push directly to main"
    - "Skip development branch"
  environments:
    development: "auto-deploy on merge"
    uat: "auto-deploy on merge, requires testing"
    production: "requires 2 approvals"
