# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this contact belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["tenant", "last_name", "first_name"],
                name="contacts_co_tenant__9ed7d7_idx",
            ),
        ),
    ]
