# Generated by Django 6.0 on 2026-01-10 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_tenant_and_more"),
        ("customers", "0005_customer_industry_array_and_more"),
        ("suppliers", "0005_supplier_departments_array"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer this contact belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_persons",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier this contact belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_persons",
                to="suppliers.supplier",
            ),
        ),
    ]
