# Generated by Django 4.2.7 on 2025-09-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the purchase order', max_length=20)),
                ('order_date', models.DateField(help_text='Date the order was placed')),
                ('delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('supplier', models.ForeignKey(help_text='Supplier for this purchase order', on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date', '-created_on'],
            },
        ),
    ]
