# Generated by Django 4.2.7 on 2025-10-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carriers", "0003_carrier_account_line_of_credit_and_more"),
        ("contacts", "0003_contact_cell_phone_contact_contact_title_and_more"),
        ("plants", "0003_plant_plant_est_num"),
        ("purchase_orders", "0002_purchaseorder_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                help_text="Carrier for this purchase order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carriers.carrier",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="carrier_release_format",
            field=models.CharField(
                blank=True, help_text="Carrier release format", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="carrier_release_num",
            field=models.CharField(
                blank=True, help_text="Carrier release number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary contact for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="date_time_stamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when PO was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="how_carrier_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("Fax", "Fax"),
                ],
                help_text="How carrier makes appointments",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="our_purchase_order_num",
            field=models.CharField(
                blank=True,
                help_text="Our internal purchase order number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="pick_up_date",
            field=models.DateField(
                blank=True, help_text="Scheduled pick up date", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Plant/facility for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="quantity",
            field=models.IntegerField(
                blank=True, help_text="Quantity of items", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_confirmation_order_num",
            field=models.CharField(
                blank=True,
                help_text="Supplier's confirmation order number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="total_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total weight",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="weight_unit",
            field=models.CharField(
                choices=[("LBS", "LBS"), ("KG", "KG")],
                default="LBS",
                help_text="Unit of weight (LBS or KG)",
                max_length=10,
            ),
        ),
    ]
