# Generated by Django 4.2.7 on 2025-10-13 05:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchase_orders", "0003_purchaseorder_carrier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="carrier_release_format",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Carrier release format",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="carrier_release_num",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Carrier release number",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="how_carrier_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("Fax", "Fax"),
                ],
                default="",
                help_text="How carrier makes appointments",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="our_purchase_order_num",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Our internal purchase order number",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier_confirmation_order_num",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Supplier's confirmation order number",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total order amount",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "changed_data",
                    models.JSONField(
                        help_text="JSON representation of changed fields and their values"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        default="updated",
                        help_text="Type of change made",
                        max_length=20,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        help_text="Purchase order this history entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="purchase_orders.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order History",
                "verbose_name_plural": "Purchase Order Histories",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["purchase_order", "-created_on"],
                        name="purchase_or_purchas_dafcda_idx",
                    )
                ],
            },
        ),
    ]
