# Generated by Django 4.2.7 on 2025-10-13 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchase_orders", "0004_alter_purchaseorder_carrier_release_format_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "changed_data",
                    models.JSONField(
                        help_text="JSON representation of changed fields and their values"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        default="updated",
                        help_text="Type of change made",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order History",
                "verbose_name_plural": "Purchase Order Histories",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AlterModelOptions(
            name="carrierpurchaseorder",
            options={
                "ordering": ["-date_time_stamp_created", "-created_on"],
                "verbose_name": "Carrier Purchase Order",
                "verbose_name_plural": "Carrier Purchase Orders",
            },
        ),
        migrations.RemoveIndex(
            model_name="carrierpurchaseorder",
            name="purchase_or_purchas_dafcda_idx",
        ),
        migrations.RemoveField(
            model_name="carrierpurchaseorder",
            name="change_type",
        ),
        migrations.RemoveField(
            model_name="carrierpurchaseorder",
            name="changed_by",
        ),
        migrations.RemoveField(
            model_name="carrierpurchaseorder",
            name="changed_data",
        ),
        migrations.RemoveField(
            model_name="carrierpurchaseorder",
            name="purchase_order",
        ),
        migrations.AlterField(
            model_name="carrierpurchaseorder",
            name="net_or_catch",
            field=models.CharField(
                blank=True,
                choices=[("Net", "Net"), ("Catch", "Catch")],
                default="",
                help_text="Weight type (Net or Catch)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderhistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made the change",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderhistory",
            name="purchase_order",
            field=models.ForeignKey(
                help_text="Purchase order this history entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="purchase_orders.purchaseorder",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderhistory",
            index=models.Index(
                fields=["purchase_order", "-created_on"],
                name="purchase_or_purchas_dafcda_idx",
            ),
        ),
    ]
