# Generated by Django 4.2.7 on 2025-09-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
        ("core", "0001_initial"),
        ("contacts", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="accounting_line_of_credit",
            field=models.CharField(
                blank=True, help_text="Line of credit amount", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="accounting_terms",
            field=models.CharField(
                blank=True, help_text="Accounting terms", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Multiple contacts associated with this supplier",
                related_name="suppliers",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="country_origin",
            field=models.CharField(
                blank=True,
                help_text="Country of origin (e.g., U.S, CAN)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="credit_app_sent",
            field=models.BooleanField(
                default=False, help_text="Has credit application been sent?"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="credit_app_set_up",
            field=models.BooleanField(
                default=False, help_text="Has credit application been set up?"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="edible_inedible",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Edible", "Edible"),
                    ("Inedible", "Inedible"),
                    ("Edible & Inedible", "Edible & Inedible"),
                ],
                help_text="Type of products supplied",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="how_to_book_pickup",
            field=models.CharField(
                blank=True,
                help_text="How to book pickup (e.g., Website, Call)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="offer_contracts",
            field=models.BooleanField(
                default=False, help_text="Does supplier offer contracts?"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="offers_export_documents",
            field=models.BooleanField(
                default=False, help_text="Does supplier offer export documents?"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="origin",
            field=models.CharField(
                blank=True,
                help_text="Product origin (e.g., Domestic, Imported)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated plant establishment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="proteins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Protein types supplied by this supplier",
                to="core.protein",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="shipping_offered",
            field=models.CharField(
                blank=True,
                help_text="Shipping services offered (e.g., Yes - Domestic)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="Street address (alternative to address field)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="tested_product",
            field=models.BooleanField(
                default=False, help_text="Does supplier provide tested products?"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="type_of_certificate",
            field=models.CharField(
                blank=True,
                help_text="Certificate type (e.g., 3rd Party, BRC)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="type_of_plant",
            field=models.CharField(
                blank=True,
                help_text="Type of plant (e.g., Vertical, Processor)",
                max_length=100,
            ),
        ),
    ]
