# Generated by Django 4.2.7 on 2025-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_add_defaults_for_postgres_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='package_type',
            field=models.CharField(blank=True, choices=[('Boxed wax lined', 'Boxed wax lined'), ('Boxed CO2', 'Boxed CO2'), ('Combo bins', 'Combo bins'), ('Totes', 'Totes'), ('Bags', 'Bags'), ('Bulk', 'Bulk'), ('Poly-Multiple', 'Poly-Multiple'), ('Nude', 'Nude')], default='', help_text='Package type (e.g., Boxed wax lined, Combo bins)', max_length=50),
        ),
    ]
