# Generated by Django 4.2.7 on 2025-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_contact_cell_phone_contact_contact_title_and_more"),
        ("carriers", "0002_carrier_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="account_line_of_credit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("$0 - $50,000", "$0 - $50,000"),
                    ("$50,000 - $100,000", "$50,000 - $100,000"),
                    ("$100,000 - $250,000", "$100,000 - $250,000"),
                    ("$250,000 - $500,000", "$250,000 - $500,000"),
                    ("$500,000 - $1,000,000", "$500,000 - $1,000,000"),
                    ("$1,000,000+", "$1,000,000+"),
                ],
                help_text="Line of credit amount range",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="accounting_payable_contact_email",
            field=models.EmailField(
                blank=True, help_text="Accounting payable contact email", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="accounting_payable_contact_name",
            field=models.CharField(
                blank=True, help_text="Accounting payable contact name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="accounting_payable_contact_phone",
            field=models.CharField(
                blank=True, help_text="Accounting payable contact phone", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="accounting_payment_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire", "Wire"),
                    ("ACH", "ACH"),
                    ("Check", "Check"),
                    ("Credit Card", "Credit Card"),
                ],
                help_text="Payment terms (e.g., Wire, ACH, Check)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Multiple contacts associated with this carrier",
                related_name="carriers",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="credit_limits",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire 1 day prior", "Wire 1 day prior"),
                    ("Net 7", "Net 7"),
                    ("Net 15", "Net 15"),
                    ("Net 30", "Net 30"),
                    ("Net 45", "Net 45"),
                    ("Net 60", "Net 60"),
                ],
                help_text="Credit limits/terms (e.g., Net 30, Wire 1 day prior)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="departments",
            field=models.CharField(
                blank=True,
                help_text="Departments (comma-separated: BOL, COA, POD, etc.)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="how_carrier_make_appointment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("Website", "Website"),
                    ("Fax", "Fax"),
                ],
                help_text="How carrier makes appointments (e.g., Email, Phone)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="my_customer_num_from_carrier",
            field=models.CharField(
                blank=True,
                help_text="Our customer number with this carrier",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="sales_contact_email",
            field=models.EmailField(
                blank=True, help_text="Sales contact email", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="sales_contact_name",
            field=models.CharField(
                blank=True, help_text="Sales contact name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="sales_contact_phone",
            field=models.CharField(
                blank=True, help_text="Sales contact phone", max_length=20
            ),
        ),
    ]
