# Generated by Django 4.2.7 on 2025-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0002_plant_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="plant_est_num",
            field=models.CharField(
                blank=True, help_text="Plant establishment number", max_length=50
            ),
        ),
    ]
