# Generated by Django 4.2.7 on 2025-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_plant_est_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='plant',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_est_num',
            field=models.CharField(blank=True, default='', help_text='Plant establishment number', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
