# Generated by Django 4.2.7 on 2025-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='actual_behavior',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='expected_behavior',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='os',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='reporter_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='screen_resolution',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
