# Generated by Django 4.2.7 on 2025-09-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Customer company name', max_length=255)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person name', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Customer address', null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State or province', max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='ZIP or postal code', max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
