# Generated by Django 4.2.7 on 2025-09-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
        ("core", "0001_initial"),
        ("contacts", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="accounting_line_of_credit",
            field=models.CharField(
                blank=True,
                help_text="Line of credit amount (e.g., $50,000 - $100,000)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="accounting_terms",
            field=models.CharField(
                blank=True,
                help_text="Accounting terms (e.g., Wire, ACH)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Multiple contacts associated with this customer",
                related_name="customers",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="edible_inedible",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Edible", "Edible"),
                    ("Inedible", "Inedible"),
                    ("Edible & Inedible", "Edible & Inedible"),
                ],
                help_text="Type of products handled",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Industry sector (e.g., Pet Sector, Retail)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated plant establishment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="proteins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Protein types handled by this customer",
                to="core.protein",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="purchasing_preference_origin",
            field=models.CharField(
                blank=True,
                help_text="Purchasing preference origin (e.g., Domestic, Imported)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="Street address (alternative to address field)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="type_of_plant",
            field=models.CharField(
                blank=True,
                help_text="Customer type of plant (e.g., Vertical, Processor)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="will_pickup_load",
            field=models.BooleanField(
                default=False, help_text="Will customer pickup load?"
            ),
        ),
    ]
