# Generated by Django 4.2.7 on 2025-10-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("customers", "0002_customer_accounting_line_of_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this customer",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="tenants.tenant",
            ),
        ),
    ]
