# Generated by Django 4.2.7 on 2025-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customer_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="account_line_of_credit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("$0 - $50,000", "$0 - $50,000"),
                    ("$50,000 - $100,000", "$50,000 - $100,000"),
                    ("$100,000 - $250,000", "$100,000 - $250,000"),
                    ("$250,000 - $500,000", "$250,000 - $500,000"),
                    ("$500,000 - $1,000,000", "$500,000 - $1,000,000"),
                    ("$1,000,000+", "$1,000,000+"),
                ],
                help_text="Line of credit amount range",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="accounting_payment_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire", "Wire"),
                    ("ACH", "ACH"),
                    ("Check", "Check"),
                    ("Credit Card", "Credit Card"),
                ],
                help_text="Payment terms (e.g., Wire, ACH, Check)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="buyer_contact_email",
            field=models.EmailField(
                blank=True, help_text="Buyer contact email", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="buyer_contact_name",
            field=models.CharField(
                blank=True, help_text="Buyer contact name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="buyer_contact_phone",
            field=models.CharField(
                blank=True, help_text="Buyer contact phone", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limits",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Wire 1 day prior", "Wire 1 day prior"),
                    ("Net 7", "Net 7"),
                    ("Net 15", "Net 15"),
                    ("Net 30", "Net 30"),
                    ("Net 45", "Net 45"),
                    ("Net 60", "Net 60"),
                ],
                help_text="Credit limits/terms (e.g., Net 30, Wire 1 day prior)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="product_exportable",
            field=models.BooleanField(
                default=False, help_text="Does customer require exportable products?"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="type_of_certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3rd Party", "3rd Party"),
                    ("BRC", "BRC"),
                    ("SQF", "SQF"),
                    ("Halal", "Halal"),
                    ("Kosher", "Kosher"),
                    ("Organic", "Organic"),
                ],
                help_text="Certificate type required (e.g., 3rd Party, BRC)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="accounting_line_of_credit",
            field=models.CharField(
                blank=True,
                help_text="Line of credit amount (deprecated, use account_line_of_credit)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="accounting_terms",
            field=models.CharField(
                blank=True,
                help_text="Accounting terms (deprecated, use accounting_payment_terms)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pet Sector", "Pet Sector"),
                    ("Processor", "Processor"),
                    ("Retail", "Retail"),
                    ("Food Service", "Food Service"),
                    ("Export", "Export"),
                ],
                help_text="Industry sector (e.g., Pet Sector, Retail)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="purchasing_preference_origin",
            field=models.CharField(
                blank=True,
                choices=[("Domestic", "Domestic"), ("Imported", "Imported")],
                help_text="Purchasing preference origin (e.g., Domestic, Imported)",
                max_length=100,
            ),
        ),
    ]
