# Generated by Django 4.2.7 on 2025-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_account_line_of_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_line_of_credit',
            field=models.CharField(blank=True, choices=[('$0 - $50,000', '$0 - $50,000'), ('$50,000 - $100,000', '$50,000 - $100,000'), ('$100,000 - $250,000', '$100,000 - $250,000'), ('$250,000 - $500,000', '$250,000 - $500,000'), ('$500,000 - $1,000,000', '$500,000 - $1,000,000'), ('$1,000,000+', '$1,000,000+')], default='', help_text='Line of credit amount range', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accounting_line_of_credit',
            field=models.CharField(blank=True, default='', help_text='Line of credit amount (deprecated, use account_line_of_credit)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accounting_payment_terms',
            field=models.CharField(blank=True, choices=[('Wire', 'Wire'), ('ACH', 'ACH'), ('Check', 'Check'), ('Credit Card', 'Credit Card')], default='', help_text='Payment terms (e.g., Wire, ACH, Check)', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accounting_terms',
            field=models.CharField(blank=True, default='', help_text='Accounting terms (deprecated, use accounting_payment_terms)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='buyer_contact_email',
            field=models.EmailField(blank=True, default='', help_text='Buyer contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='buyer_contact_name',
            field=models.CharField(blank=True, default='', help_text='Buyer contact name', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='buyer_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Buyer contact phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limits',
            field=models.CharField(blank=True, choices=[('Wire 1 day prior', 'Wire 1 day prior'), ('Net 7', 'Net 7'), ('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 45', 'Net 45'), ('Net 60', 'Net 60')], default='', help_text='Credit limits/terms (e.g., Net 30, Wire 1 day prior)', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='edible_inedible',
            field=models.CharField(blank=True, choices=[('Edible', 'Edible'), ('Inedible', 'Inedible'), ('Edible & Inedible', 'Edible & Inedible')], default='', help_text='Type of products handled', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, choices=[('Pet Sector', 'Pet Sector'), ('Processor', 'Processor'), ('Retail', 'Retail'), ('Food Service', 'Food Service'), ('Export', 'Export')], default='', help_text='Industry sector (e.g., Pet Sector, Retail)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchasing_preference_origin',
            field=models.CharField(blank=True, choices=[('Domestic', 'Domestic'), ('Imported', 'Imported')], default='', help_text='Purchasing preference origin (e.g., Domestic, Imported)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_address',
            field=models.CharField(blank=True, default='', help_text='Street address (alternative to address field)', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type_of_certificate',
            field=models.CharField(blank=True, choices=[('3rd Party', '3rd Party'), ('BRC', 'BRC'), ('SQF', 'SQF'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Organic', 'Organic')], default='', help_text='Certificate type required (e.g., 3rd Party, BRC)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type_of_plant',
            field=models.CharField(blank=True, default='', help_text='Customer type of plant (e.g., Vertical, Processor)', max_length=100),
        ),
    ]
