# Generated by Django 5.2.9 on 2025-12-07 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="schema_name",
        ),
    ]
