# Generated by Django 4.2.7 on 2025-11-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_alter_tenant_contact_phone_tenantinvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Tenant logo image for branding",
                null=True,
                upload_to="tenant_logos/",
            ),
        ),
    ]
