# Generated by Django 4.2.7 on 2025-11-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_tenant_logo"),
    ]

    operations = [
        # Add schema_name column only if it doesn't exist (idempotent)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN 
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='tenants_tenant' AND column_name='schema_name'
                    ) THEN 
                        ALTER TABLE tenants_tenant ADD COLUMN schema_name VARCHAR(63) NULL;
                        CREATE UNIQUE INDEX IF NOT EXISTS tenants_tenant_schema_name_uniq ON tenants_tenant(schema_name);
                    END IF; 
                END $$;
            """,
            reverse_sql="ALTER TABLE tenants_tenant DROP COLUMN IF EXISTS schema_name CASCADE;",
        ),
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domain name (e.g., 'tenant.example.com' or 'tenant.localhost')",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the primary domain for the tenant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant associated with this domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_tenantdomain",
                "ordering": ["domain"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="tenants_ten_domain_6df599_idx"
                    ),
                    models.Index(
                        fields=["tenant", "is_primary"],
                        name="tenants_ten_tenant__3bd559_idx",
                    ),
                ],
            },
        ),
    ]
