# Generated by Django 4.2.7 on 2025-11-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_tenant_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="schema_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Database schema name (for future django-tenants compatibility)",
                max_length=63,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domain name (e.g., 'tenant.example.com' or 'tenant.localhost')",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the primary domain for the tenant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant associated with this domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_domain",
                "ordering": ["domain"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="tenants_dom_domain_6df599_idx"
                    ),
                    models.Index(
                        fields=["tenant", "is_primary"],
                        name="tenants_dom_tenant__3bd559_idx",
                    ),
                ],
            },
        ),
    ]
