# Generated by Django 4.2.7 on 2025-11-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_schema_name_and_domain_model'),
        ('tenants', '0004_client_domain'),
    ]

    operations = [
    ]
