# Generated by Django 4.2.7 on 2025-11-29 02:00
# Modified to be idempotent - index rename operations are now no-ops
# Migration 0005 already created indexes with proper custom names.
# Django auto-generated this migration expecting different index names that don't exist.

import django.db.models.deletion
from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor):
    """
    Intentionally empty - migration 0005 already created indexes with proper names.
    Django auto-generated this migration expecting different index names, but since
    migration 0005 used custom SQL to create indexes, those names don't exist.
    The indexes are already present with better names, so no action needed.
    """
    pass


def reverse_rename_index(apps, schema_editor):
    """Reverse operation - intentionally empty (see forward migration)"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_client_domain"),
    ]

    operations = [
        migrations.RunPython(
            rename_index_if_exists,
            reverse_code=reverse_rename_index,
        ),
        migrations.AlterField(
            model_name="client",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                help_text="PostgreSQL schema name for this client",
                max_length=63,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(
                db_index=True,
                help_text="Domain name (e.g., 'client.example.com')",
                max_length=253,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this is the primary domain for the client",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                help_text="Client associated with this domain",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.client",
            ),
        ),
    ]
