# Generated by Django 4.2.7 on 2025-11-29 02:00
# Modified to be idempotent - checks for index existence before renaming

import django.db.models.deletion
from django.db import migrations, models, connection


def rename_index_if_exists(apps, schema_editor):
    """Rename indexes only if they exist (idempotent)"""
    with connection.cursor() as cursor:
        # Check if old indexes exist and rename them
        # Index 1: domain field index
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = 'tenants_ten_domain_6df599_idx'
                ) THEN
                    ALTER INDEX tenants_ten_domain_6df599_idx 
                    RENAME TO tenants_ten_domain_f3abe6_idx;
                END IF;
            END $$;
        """)
        
        # Index 2: tenant_id field index
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = 'tenants_ten_tenant__3bd559_idx'
                ) THEN
                    ALTER INDEX tenants_ten_tenant__3bd559_idx 
                    RENAME TO tenants_ten_tenant__f55360_idx;
                END IF;
            END $$;
        """)


def reverse_rename_index(apps, schema_editor):
    """Reverse operation - rename indexes back if they exist"""
    with connection.cursor() as cursor:
        # Reverse Index 1
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = 'tenants_ten_domain_f3abe6_idx'
                ) THEN
                    ALTER INDEX tenants_ten_domain_f3abe6_idx 
                    RENAME TO tenants_ten_domain_6df599_idx;
                END IF;
            END $$;
        """)
        
        # Reverse Index 2
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = 'tenants_ten_tenant__f55360_idx'
                ) THEN
                    ALTER INDEX tenants_ten_tenant__f55360_idx 
                    RENAME TO tenants_ten_tenant__3bd559_idx;
                END IF;
            END $$;
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_client_domain"),
    ]

    operations = [
        migrations.RunPython(
            rename_index_if_exists,
            reverse_code=reverse_rename_index,
        ),
        migrations.AlterField(
            model_name="client",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                help_text="PostgreSQL schema name for this client",
                max_length=63,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(
                db_index=True,
                help_text="Domain name (e.g., 'client.example.com')",
                max_length=253,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this is the primary domain for the client",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                help_text="Client associated with this domain",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.client",
            ),
        ),
    ]
