# Generated by Django 4.2.7 on 2025-11-29 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_client_domain"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantdomain",
            new_name="tenants_ten_domain_f3abe6_idx",
            old_name="tenants_ten_domain_6df599_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdomain",
            new_name="tenants_ten_tenant__f55360_idx",
            old_name="tenants_ten_tenant__3bd559_idx",
        ),
        migrations.AlterField(
            model_name="client",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                help_text="PostgreSQL schema name for this client",
                max_length=63,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(
                db_index=True,
                help_text="Domain name (e.g., 'client.example.com')",
                max_length=253,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this is the primary domain for the client",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                help_text="Client associated with this domain",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.client",
            ),
        ),
    ]
