# Generated by Django 4.2.7 on 2025-12-01 11:00
# Modified to be idempotent - no-op migration

from django.db import migrations


def noop_forward(apps, schema_editor):
    """
    No-op migration. Django detected index name changes but the indexes
    are already properly named from migration 0006.
    
    This migration exists to satisfy Django's migration state but performs
    no database operations since the database is already in the correct state.
    """
    pass


def noop_reverse(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_rename_tenants_ten_domain_6df599_idx_tenants_ten_domain_f3abe6_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            noop_forward,
            reverse_code=noop_reverse,
        ),
    ]
