# Generated by Django 4.2.7 on 2025-12-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0006_rename_tenants_ten_domain_6df599_idx_tenants_ten_domain_f3abe6_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantdomain",
            new_name="tenants_ten_domain_f3abe6_idx",
            old_name="tenants_ten_domain_6df599_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdomain",
            new_name="tenants_ten_tenant__f55360_idx",
            old_name="tenants_ten_tenant__3bd559_idx",
        ),
    ]
