# Generated by Django 4.2.7 on 2025-12-01 15:17
# Modified to safely handle index renames while keeping Django state in sync

from django.db import migrations


def rename_indexes_safe(apps, schema_editor):
    """
    Safely rename indexes to stable names in the database.
    Handles permission errors by creating new indexes if rename fails.
    """
    with schema_editor.connection.cursor() as cursor:
        # Get existing indexes
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE tablename = 'tenants_tenantdomain'
            AND schemaname = 'public'
        """)
        existing = {row[0] for row in cursor.fetchall()}
        
        # Rename or create domain index
        domain_old_names = [
            'tenants_ten_domain_6df599_idx',
            'tenants_ten_domain_f3abe6_idx',
            'tenants_domain_domain_idx',
        ]
        
        if 'td_domain_idx' not in existing:
            renamed = False
            for old_name in domain_old_names:
                if old_name in existing:
                    try:
                        cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "td_domain_idx"')
                        renamed = True
                        break
                    except Exception as e:
                        # If rename fails (e.g., insufficient privileges), we'll create new index
                        print(f"Could not rename {old_name}: {e}. Will create new index instead.")
                        continue
            if not renamed:
                # Create new index (IF NOT EXISTS handles the case where index exists but we couldn't rename)
                cursor.execute('CREATE INDEX IF NOT EXISTS td_domain_idx ON tenants_tenantdomain(domain)')
        
        # Rename or create tenant/primary index
        tenant_old_names = [
            'tenants_ten_tenant__3bd559_idx',
            'tenants_ten_tenant__f55360_idx',
        ]
        
        if 'td_tenant_primary_idx' not in existing:
            renamed = False
            for old_name in tenant_old_names:
                if old_name in existing:
                    try:
                        cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "td_tenant_primary_idx"')
                        renamed = True
                        break
                    except Exception as e:
                        print(f"Could not rename {old_name}: {e}. Will create new index instead.")
                        continue
            if not renamed:
                cursor.execute('CREATE INDEX IF NOT EXISTS td_tenant_primary_idx ON tenants_tenantdomain(tenant_id, is_primary)')
            if not renamed:
                cursor.execute('CREATE INDEX IF NOT EXISTS td_tenant_primary_idx ON tenants_tenantdomain(tenant_id, is_primary)')


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_stable_index_names"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    rename_indexes_safe,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                # Tell Django's state about the new index names
                migrations.RenameIndex(
                    model_name="tenantdomain",
                    old_name="tenants_ten_domain_6df599_idx",
                    new_name="td_domain_idx",
                ),
                migrations.RenameIndex(
                    model_name="tenantdomain",
                    old_name="tenants_ten_tenant__3bd559_idx",
                    new_name="td_tenant_primary_idx",
                ),
            ],
        ),
    ]
