# Generated by Django 4.2.7 on 2025-12-01 15:17
# Modified to safely handle index renames while keeping Django state in sync

from django.db import migrations


def rename_indexes_safe(apps, schema_editor):
    """
    Safely rename indexes to stable names in the database.
    Handles permission errors by creating new indexes if rename fails.
    Uses savepoints to avoid transaction abort issues.
    
    IMPORTANT: This migration checks if tenants_tenantdomain table exists first.
    If it doesn't exist (e.g., fresh database), it's a no-op.
    """
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if table exists first
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'tenants_tenantdomain'
            )
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            print("Table tenants_tenantdomain does not exist - skipping index migration")
            return
        
        # Get existing indexes
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE tablename = 'tenants_tenantdomain'
            AND schemaname = 'public'
        """)
        existing = {row[0] for row in cursor.fetchall()}
        
        # Rename or create domain index
        domain_old_names = [
            'tenants_ten_domain_6df599_idx',
            'tenants_ten_domain_f3abe6_idx',
            'tenants_domain_domain_idx',
        ]
        
        if 'td_domain_idx' not in existing:
            renamed = False
            for old_name in domain_old_names:
                if old_name in existing:
                    # Use savepoint to isolate potential failures
                    sid = connection.savepoint()
                    try:
                        cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "td_domain_idx"')
                        connection.savepoint_commit(sid)
                        renamed = True
                        break
                    except Exception as e:
                        # Rollback to savepoint on error
                        connection.savepoint_rollback(sid)
                        print(f"Could not rename {old_name}: {e}. Will try next or create new index.")
                        continue
            
            if not renamed:
                # Create new index if rename failed or no old index found
                sid = connection.savepoint()
                try:
                    cursor.execute('CREATE INDEX IF NOT EXISTS td_domain_idx ON tenants_tenantdomain(domain)')
                    connection.savepoint_commit(sid)
                except Exception as e:
                    connection.savepoint_rollback(sid)
                    print(f"Could not create td_domain_idx: {e}")
        
        # Rename or create tenant/primary index
        tenant_old_names = [
            'tenants_ten_tenant__3bd559_idx',
            'tenants_ten_tenant__f55360_idx',
        ]
        
        if 'td_tenant_primary_idx' not in existing:
            renamed = False
            for old_name in tenant_old_names:
                if old_name in existing:
                    sid = connection.savepoint()
                    try:
                        cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "td_tenant_primary_idx"')
                        connection.savepoint_commit(sid)
                        renamed = True
                        break
                    except Exception as e:
                        connection.savepoint_rollback(sid)
                        print(f"Could not rename {old_name}: {e}. Will try next or create new index.")
                        continue
            
            if not renamed:
                sid = connection.savepoint()
                try:
                    cursor.execute('CREATE INDEX IF NOT EXISTS td_tenant_primary_idx ON tenants_tenantdomain(tenant_id, is_primary)')
                    connection.savepoint_commit(sid)
                except Exception as e:
                    connection.savepoint_rollback(sid)
                    print(f"Could not create td_tenant_primary_idx: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_stable_index_names"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    rename_indexes_safe,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                # Tell Django's state about the new index names
                migrations.RenameIndex(
                    model_name="tenantdomain",
                    old_name="tenants_ten_domain_6df599_idx",
                    new_name="td_domain_idx",
                ),
                migrations.RenameIndex(
                    model_name="tenantdomain",
                    old_name="tenants_ten_tenant__3bd559_idx",
                    new_name="td_tenant_primary_idx",
                ),
            ],
        ),
    ]
