# Generated by Django 4.2.7 on 2025-12-04 12:33
#
# NOTE: This migration is deprecated. The Client and Domain models
# are removed in migration 0012_purge_legacy_architecture.py as part
# of the transition to strict shared-schema multi-tenancy.

from django.db import migrations, models
import django.db.models.deletion

# Conditional import for backward compatibility
# django-tenants is no longer required after architecture purge
try:
    import django_tenants.postgresql_backend.base
    _check_schema_name = django_tenants.postgresql_backend.base._check_schema_name
except ImportError:
    # Fallback validator when django-tenants is not installed
    def _check_schema_name(value):
        """Dummy validator for schema names when django-tenants is not available."""
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_fix_index_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                max_length=63,
                unique=True,
                validators=[_check_schema_name],
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.client",
            ),
        ),
    ]
