# Generated by Django 5.2.9 on 2025-12-06 09:57
# Modified to be idempotent: checks if column exists before adding

from django.db import migrations


class Migration(migrations.Migration):
    """
    Idempotent migration to add schema_name field to Tenant model.
    
    This migration uses RunSQL to check if the column exists before adding it,
    making it safe to run multiple times. This is necessary because the column
    may have been added in a previous migration (0004_add_schema_name_and_domain_model.py)
    depending on the database state.
    """

    dependencies = [
        ("tenants", "0010_schema_based_client_domain"),
    ]

    operations = [
        # Add schema_name column only if it doesn't exist (idempotent)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN 
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='tenants_tenant' AND column_name='schema_name'
                    ) THEN 
                        ALTER TABLE tenants_tenant ADD COLUMN schema_name VARCHAR(63) NULL UNIQUE;
                        CREATE UNIQUE INDEX IF NOT EXISTS tenants_tenant_schema_name_uniq ON tenants_tenant(schema_name);
                    END IF; 
                END $$;
            """,
            reverse_sql="ALTER TABLE tenants_tenant DROP COLUMN IF EXISTS schema_name CASCADE;",
        ),
    ]
