# Generated by Django 5.2.9 on 2025-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_schema_based_client_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="schema_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Database schema name (for future django-tenants compatibility)",
                max_length=63,
                null=True,
                unique=True,
            ),
        ),
    ]
