# Generated by Django 5.2.9 on 2025-12-06 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0011_remove_schema_based_models"),
        ("tenants", "0011_tenant_schema_name"),
    ]

    operations = []
