# Generated by Django manually to fix schema drift
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_schema_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 1. Tell Django the field exists (Satisfies 'makemigrations --check')
            state_operations=[
                migrations.AddField(
                    model_name='tenant',
                    name='schema_name',
                    field=models.CharField(blank=True, db_index=True, help_text='Database schema name', max_length=63, null=True, unique=True),
                ),
            ],
            # 2. Do NOTHING to the database (Prevents 'column already exists' error)
            database_operations=[],
        ),
    ]
