# Generated by Django 4.2.7 on 2025-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='carrier_release_num',
            field=models.CharField(blank=True, default='', help_text='Carrier release number', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_po_num',
            field=models.CharField(blank=True, default='', help_text='Delivery PO number', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes'),
        ),
    ]
