# Generated by Django 4.2.7 on 2025-10-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales_orders", "0001_initial"),
        ("tenants", "0001_initial"),
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Related sales order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales_orders.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant that owns this invoice",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="tenants.tenant",
            ),
        ),
    ]
