# Generated by Django 4.2.7 on 2025-10-13 05:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='accounting_payable_contact_email',
            field=models.EmailField(blank=True, default='', help_text='Accounting payable contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='accounting_payable_contact_name',
            field=models.CharField(blank=True, default='', help_text='Accounting payable contact name', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='accounting_payable_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Accounting payable contact phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_po_num',
            field=models.CharField(blank=True, default='', help_text='Delivery PO number', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description_of_product_item',
            field=models.TextField(blank=True, default='', help_text='Description of product item'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='edible_or_inedible',
            field=models.CharField(blank=True, choices=[('Edible', 'Edible'), ('Inedible', 'Inedible'), ('Edible & Inedible', 'Edible & Inedible')], default='', help_text='Edible or inedible product', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='our_sales_order_num',
            field=models.CharField(blank=True, default='', help_text='Our sales order number', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type_of_protein',
            field=models.CharField(blank=True, default='', help_text='Type of protein', max_length=100),
        ),
    ]
