# Generated by Django 6.0 on 2026-01-10 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0005_plant_supplier"),
        ("suppliers", "0005_supplier_departments_array"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated plant establishment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_assignments",
                to="plants.plant",
            ),
        ),
    ]
