# Generated by Django 4.2.7 on 2025-12-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("accounts_receivables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsreceivable",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_receivables",
                to="customers.customer",
            ),
        ),
    ]
