# Generated by Django 4.2.7 on 2025-10-13 05:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivables', '0002_accountsreceivable_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsreceivable',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountsreceivable',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
