# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_receivables", "0001_initial"),
        ("customers", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsreceivable",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                help_text="Tenant this accounts receivable belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_receivables",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="accountsreceivable",
            index=models.Index(
                fields=["tenant", "invoice_number"],
                name="accounts_re_tenant__f66a87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountsreceivable",
            index=models.Index(
                fields=["tenant", "status"], name="accounts_re_tenant__60de31_idx"
            ),
        ),
    ]
