# Generated by Django 6.0 on 2025-12-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_tenant_field_if_not_exists(apps, schema_editor):
    """Add tenant field only if it doesn't exist"""
    from django.db import connection
    import uuid
    
    with connection.cursor() as cursor:
        # Check if tenant_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema='public' AND table_name='accounts_receivables_accountsreceivable' 
            AND column_name='tenant_id';
        """)
        
        if not cursor.fetchone():
            # Check if any tenants exist
            cursor.execute("SELECT id FROM tenants_tenant LIMIT 1;")
            result = cursor.fetchone()
            
            if result:
                # Production path: Tenant exists, use it as default
                default_tenant_id = result[0]
                cursor.execute("""
                    ALTER TABLE accounts_receivables_accountsreceivable 
                    ADD COLUMN tenant_id UUID NOT NULL DEFAULT %s 
                    REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;
                """, [default_tenant_id])
                
                # Remove the default after adding the column
                cursor.execute("""
                    ALTER TABLE accounts_receivables_accountsreceivable 
                    ALTER COLUMN tenant_id DROP DEFAULT;
                """)
            else:
                # Test/Fresh DB path: No tenants exist yet, add as nullable
                # Model definition will enforce non-null at application level
                cursor.execute("""
                    ALTER TABLE accounts_receivables_accountsreceivable 
                    ADD COLUMN tenant_id UUID NULL 
                    REFERENCES tenants_tenant(id) DEFERRABLE INITIALLY DEFERRED;
                """)


def add_indexes_if_not_exist(apps, schema_editor):
    """Add indexes only if they don't exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check and add first index
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename='accounts_receivables_accountsreceivable' 
            AND indexname='accounts_re_tenant__f66a87_idx';
        """)
        
        if not cursor.fetchone():
            cursor.execute("""
                CREATE INDEX accounts_re_tenant__f66a87_idx 
                ON accounts_receivables_accountsreceivable (tenant_id, invoice_number);
            """)
        
        # Check and add second index
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename='accounts_receivables_accountsreceivable' 
            AND indexname='accounts_re_tenant__60de31_idx';
        """)
        
        if not cursor.fetchone():
            cursor.execute("""
                CREATE INDEX accounts_re_tenant__60de31_idx 
                ON accounts_receivables_accountsreceivable (tenant_id, status);
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_receivables", "0001_initial"),
        ("customers", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_tenant_field_if_not_exists, migrations.RunPython.noop),
        migrations.RunPython(add_indexes_if_not_exist, migrations.RunPython.noop),
    ]
