# Generated by Django 6.0 on 2026-01-04 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_receivables", "0003_state_sync_tenant"),
        ("customers", "0003_customer_contact_title_alter_customer_industry"),
        ("tenants", "0006_metadata_lockdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accountsreceivable",
            index=models.Index(
                fields=["tenant", "invoice_number"],
                name="accounts_re_tenant__f66a87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountsreceivable",
            index=models.Index(
                fields=["tenant", "status"], name="accounts_re_tenant__60de31_idx"
            ),
        ),
    ]
