# Generated by Django 4.2.7 on 2025-10-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0006_alter_supplier_package_type"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="carton_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Waxed Lined", "Waxed Lined"),
                    ("Cardboard", "Cardboard"),
                    ("Plastic", "Plastic"),
                ],
                default="",
                help_text="Type of carton (e.g., Poly-Multiple, Waxed Lined)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="namp",
            field=models.CharField(
                blank=True, default="", help_text="NAMP code", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[("Domestic", "Domestic"), ("Imported", "Imported")],
                default="",
                help_text="Product origin (Packer, Boxed Cold Storage)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pcs_per_carton",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pieces per carton (e.g., 4/10)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="plants_available",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Plants where product is available (e.g., TX, WI, MI)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier for this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_item_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Supplier's item number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ub",
            field=models.CharField(
                blank=True,
                default="",
                help_text="UB code (auto-generated/pulled)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="uom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unit of measure (LB, KG)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="usda",
            field=models.CharField(
                blank=True,
                default="",
                help_text="USDA code (auto-generated/pulled)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="edible_or_inedible",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Edible", "Edible"),
                    ("Inedible", "Inedible"),
                    ("Edible & Inedible", "Edible & Inedible"),
                ],
                default="",
                help_text="Edible or inedible product",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fresh_or_frozen",
            field=models.CharField(
                blank=True,
                choices=[("Fresh", "Fresh"), ("Frozen", "Frozen")],
                default="",
                help_text="Product state (Fresh or Frozen)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="net_or_catch",
            field=models.CharField(
                blank=True,
                choices=[("Net", "Net"), ("Catch", "Catch")],
                default="",
                help_text="Weight type (Net or Catch)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boxed wax lined", "Boxed wax lined"),
                    ("Boxed CO2", "Boxed CO2"),
                    ("Combo bins", "Combo bins"),
                    ("Totes", "Totes"),
                    ("Bags", "Bags"),
                    ("Bulk", "Bulk"),
                    ("Poly-Multiple", "Poly-Multiple"),
                    ("Nude", "Nude"),
                ],
                default="",
                help_text="Package type (e.g., Boxed wax lined, Combo bins)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type_of_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Pork", "Pork"),
                    ("Lamb", "Lamb"),
                    ("Turkey", "Turkey"),
                    ("Fish", "Fish"),
                    ("Horse", "Horse"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Type of protein (e.g., Beef, Chicken, Pork)",
                max_length=50,
            ),
        ),
    ]
