name: Test Deployment Failure Monitor

on:
  workflow_dispatch:
    inputs:
      simulate_component:
        description: 'Component to simulate failure for'
        required: true
        default: 'frontend'
        type: choice
        options:
        - frontend
        - backend

jobs:
  simulate-frontend-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.simulate_component == 'frontend' }}
    steps:
    - name: Simulate Frontend Deployment Failure
      run: |
        echo "Simulating frontend deployment failure..."
        echo "Error: Failed to build React app"
        echo "Module not found: Cannot resolve 'some-missing-module'"
        echo "Build failed with exit code 1"
        exit 1

  simulate-backend-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.simulate_component == 'backend' }}
    steps:
    - name: Simulate Backend Deployment Failure  
      run: |
        echo "Simulating backend deployment failure..."
        echo "Error: Database connection failed"
        echo "django.db.utils.OperationalError: FATAL: password authentication failed"
        echo "Health check failed"
        exit 1